repos:

- repo: https://github.com/psf/black
  rev: 22.6.0
  hooks:
  - id: black

- repo: https://github.com/codespell-project/codespell
  rev: v2.1.0
  hooks:
  - id: codespell
    types_or: [python, markdown]
    args: ["--ignore-words=codespell-ignore-words.txt"]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: end-of-file-fixer
    exclude: ^tests/data/
    stages: [commit, merge-commit, push, prepare-commit-msg, commit-msg, post-checkout, post-commit, post-merge, post-rewrite]
  - id: trailing-whitespace
    exclude: ^tests/data/
    stages: [commit, merge-commit, push, prepare-commit-msg, commit-msg, post-checkout, post-commit, post-merge, post-rewrite]

- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
  - id: isort

- repo: https://github.com/PyCQA/flake8
  rev: 5.0.4
  hooks:
  - id: flake8
    additional_dependencies: &flake8_dependencies
    - flake8==5.0.4
    - flake8-comprehensions==3.10.0
    - flake8-bugbear==22.7.1
